# Render.com deployment configuration
# This file configures your video downloader for Render.com

services:
  - type: web
    name: video-downloader
    env: node
    plan: free  # Change to 'starter' or higher for production
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: video-downloader
          property: port
      - key: PATH
        value: "$HOME/.local/bin:$PATH"
      - key: RENDER
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    branch: main  # Change to your main branch name
    rootDir: .
    
    # Build settings
    buildFilter:
      paths:
        - "**/*.js"
        - "**/*.json"
        - "**/*.md"
        - "!node_modules/**"
        - "!*.backup"
        - "!.git/**"
    
    # Environment detection and yt-dlp installation
    preDeployCommand: |
      echo "Setting up environment for Render.com..."
      export PATH="$HOME/.local/bin:$PATH"
      echo "PATH updated: $PATH"
      echo "Note: yt-dlp will be installed dynamically by the application if needed"
      # Check if yt-dlp is already available
      if command -v yt-dlp >/dev/null 2>&1; then
        echo "✅ yt-dlp already available: $(yt-dlp --version)"
      else
        echo "ℹ️ yt-dlp not found - will be installed dynamically by the application"
      fi
    
    # Disk storage (for temporary files)
    disk:
      name: video-temp
      mountPath: /tmp/videos
      sizeGB: 1