# Render.com deployment configuration
# This file configures your video downloader for Render.com

services:
  - type: web
    name: video-downloader
    env: node
    plan: free  # Change to 'starter' or higher for production
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: video-downloader
          property: port
      - key: PATH
        value: "$HOME/.local/bin:$PATH"
      - key: RENDER
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    branch: main  # Change to your main branch name
    rootDir: .
    
    # Build settings
    buildFilter:
      paths:
        - "**/*.js"
        - "**/*.json"
        - "**/*.md"
        - "!node_modules/**"
        - "!*.backup"
        - "!.git/**"
    
    # Environment detection and yt-dlp installation
    preDeployCommand: |
      echo "Installing yt-dlp for Render.com..."
      python3 -m pip install --user --upgrade yt-dlp
      export PATH="$HOME/.local/bin:$PATH"
      echo "PATH after update: $PATH"
      echo "Checking yt-dlp installation..."
      which yt-dlp || echo "yt-dlp not found in PATH"
      ls -la $HOME/.local/bin/ | grep yt-dlp || echo "yt-dlp not found in .local/bin"
      if command -v yt-dlp >/dev/null 2>&1; then
        echo "✅ yt-dlp version: $(yt-dlp --version)"
      else
        echo "❌ yt-dlp installation failed"
        exit 1
      fi
    
    # Disk storage (for temporary files)
    disk:
      name: video-temp
      mountPath: /tmp/videos
      sizeGB: 1